name: '${name}'
author: [ FlexingStudios, Elec7reify ]
version: '${version}'

main: com.flexingstudios.flexingnetwork.FlexingNetworkPlugin

commands:
  msg:
    aliases: [m, w, whisper, t, tell, pm, лс]
  reply:
    aliases: [r]
  ignore:
  unignore:
  msgtoggle:
  gamemode:
    aliases: [gm]
  gms:
  gmc:
  gma:
  gmsp:
  fly:
  alert:
  profile:
    aliases: [me, я, профиль]
  help:
  vanish:
    aliases: [v]
  speed:
  tp:
  hub:
    aliases: [lobby, хаб, лобби, лоби]
  stp:
  donate:
  flexingnetwork:
    aliases: [flexingworld, flex, flexing, fn, fw]
  kick:
  shadekick:
    aliases: [shkick]
  ban:
  shadeban:
    aliases: [shban]
  unban:
  shadeunban:
    aliases: [shunban]
  actions:
  restrict:
  firework:
